# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IRTS_FL_2(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # IRTS_FL_2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IRTS_FL_2
    def Channel9(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # IRTS_FL_2
    def Channel10(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # IRTS_FL_2
    def Channel11(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # IRTS_FL_2
    def Channel12(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))

def CreateIRTS_FL_2(builder, channel9, channel10, channel11, channel12):
    builder.Prep(2, 8)
    builder.PrependUint16(channel12)
    builder.PrependUint16(channel11)
    builder.PrependUint16(channel10)
    builder.PrependUint16(channel9)
    return builder.Offset()
