# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TLM_STATUS(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # TLM_STATUS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TLM_STATUS
    def TlmStatus(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TLM_STATUS
    def RaceType(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # TLM_STATUS
    def Driver(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # TLM_STATUS
    def Circuit(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(3))

def CreateTLM_STATUS(builder, tlmStatus, raceType, driver, circuit):
    builder.Prep(1, 4)
    builder.PrependUint8(circuit)
    builder.PrependUint8(driver)
    builder.PrependInt8(raceType)
    builder.PrependInt8(tlmStatus)
    return builder.Offset()
