# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BRAKE_PEDAL_VAL(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 1

    # BRAKE_PEDAL_VAL
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BRAKE_PEDAL_VAL
    def Level(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateBRAKE_PEDAL_VAL(builder, level):
    builder.Prep(1, 1)
    builder.PrependUint8(level)
    return builder.Offset()
