# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SET_PEDALS_RANGE(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 2

    # SET_PEDALS_RANGE
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SET_PEDALS_RANGE
    def SyncState(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # SET_PEDALS_RANGE
    def Pedal(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))

def CreateSET_PEDALS_RANGE(builder, syncState, pedal):
    builder.Prep(1, 2)
    builder.PrependInt8(pedal)
    builder.PrependInt8(syncState)
    return builder.Offset()
