#ifndef SCHEMA_VERIFIER_H
#define SCHEMA_VERIFIER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef SCHEMA_READER_H
#include "schema_reader.h"
#endif
#include ../../../external/flatcc/flatcc_verifier.h"
#include ../../../external/flatcc/flatcc_prologue.h"


static inline int VOLTAGES_CB0_0_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB0_0_identifier, 8, 2);
}

static inline int VOLTAGES_CB0_0_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB0_0_type_hash, 8, 2);
}

static inline int VOLTAGES_CB0_0_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB0_0_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB0_1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB0_1_identifier, 8, 2);
}

static inline int VOLTAGES_CB0_1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB0_1_type_hash, 8, 2);
}

static inline int VOLTAGES_CB0_1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB0_1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB0_2_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB0_2_identifier, 8, 2);
}

static inline int VOLTAGES_CB0_2_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB0_2_type_hash, 8, 2);
}

static inline int VOLTAGES_CB0_2_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB0_2_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB0_3_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB0_3_identifier, 8, 2);
}

static inline int VOLTAGES_CB0_3_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB0_3_type_hash, 8, 2);
}

static inline int VOLTAGES_CB0_3_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB0_3_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB0_4_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB0_4_identifier, 8, 2);
}

static inline int VOLTAGES_CB0_4_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB0_4_type_hash, 8, 2);
}

static inline int VOLTAGES_CB0_4_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB0_4_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int TEMPERATURES_CB0_0_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB0_0_identifier, 8, 1);
}

static inline int TEMPERATURES_CB0_0_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB0_0_type_hash, 8, 1);
}

static inline int TEMPERATURES_CB0_0_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 1);
}

static inline int TEMPERATURES_CB0_0_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 1);
}

static inline int TEMPERATURES_CB0_1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB0_1_identifier, 8, 1);
}

static inline int TEMPERATURES_CB0_1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB0_1_type_hash, 8, 1);
}

static inline int TEMPERATURES_CB0_1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 1);
}

static inline int TEMPERATURES_CB0_1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 1);
}

static inline int TEMPERATURES_CB0_2_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB0_2_identifier, 2, 1);
}

static inline int TEMPERATURES_CB0_2_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB0_2_type_hash, 2, 1);
}

static inline int TEMPERATURES_CB0_2_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 2, 1);
}

static inline int TEMPERATURES_CB0_2_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 2, 1);
}

static inline int VOLTAGES_CB1_0_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB1_0_identifier, 8, 2);
}

static inline int VOLTAGES_CB1_0_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB1_0_type_hash, 8, 2);
}

static inline int VOLTAGES_CB1_0_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB1_0_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB1_1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB1_1_identifier, 8, 2);
}

static inline int VOLTAGES_CB1_1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB1_1_type_hash, 8, 2);
}

static inline int VOLTAGES_CB1_1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB1_1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB1_2_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB1_2_identifier, 8, 2);
}

static inline int VOLTAGES_CB1_2_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB1_2_type_hash, 8, 2);
}

static inline int VOLTAGES_CB1_2_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB1_2_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB1_3_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB1_3_identifier, 8, 2);
}

static inline int VOLTAGES_CB1_3_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB1_3_type_hash, 8, 2);
}

static inline int VOLTAGES_CB1_3_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB1_3_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB1_4_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB1_4_identifier, 8, 2);
}

static inline int VOLTAGES_CB1_4_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB1_4_type_hash, 8, 2);
}

static inline int VOLTAGES_CB1_4_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB1_4_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int TEMPERATURES_CB1_0_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB1_0_identifier, 8, 1);
}

static inline int TEMPERATURES_CB1_0_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB1_0_type_hash, 8, 1);
}

static inline int TEMPERATURES_CB1_0_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 1);
}

static inline int TEMPERATURES_CB1_0_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 1);
}

static inline int TEMPERATURES_CB1_1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB1_1_identifier, 8, 1);
}

static inline int TEMPERATURES_CB1_1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB1_1_type_hash, 8, 1);
}

static inline int TEMPERATURES_CB1_1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 1);
}

static inline int TEMPERATURES_CB1_1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 1);
}

static inline int TEMPERATURES_CB1_2_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB1_2_identifier, 4, 1);
}

static inline int TEMPERATURES_CB1_2_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB1_2_type_hash, 4, 1);
}

static inline int TEMPERATURES_CB1_2_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 4, 1);
}

static inline int TEMPERATURES_CB1_2_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 4, 1);
}

static inline int VOLTAGES_CB2_0_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB2_0_identifier, 8, 2);
}

static inline int VOLTAGES_CB2_0_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB2_0_type_hash, 8, 2);
}

static inline int VOLTAGES_CB2_0_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB2_0_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB2_1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB2_1_identifier, 8, 2);
}

static inline int VOLTAGES_CB2_1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB2_1_type_hash, 8, 2);
}

static inline int VOLTAGES_CB2_1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB2_1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB2_2_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB2_2_identifier, 8, 2);
}

static inline int VOLTAGES_CB2_2_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB2_2_type_hash, 8, 2);
}

static inline int VOLTAGES_CB2_2_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB2_2_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB2_3_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB2_3_identifier, 8, 2);
}

static inline int VOLTAGES_CB2_3_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB2_3_type_hash, 8, 2);
}

static inline int VOLTAGES_CB2_3_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB2_3_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB2_4_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB2_4_identifier, 8, 2);
}

static inline int VOLTAGES_CB2_4_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB2_4_type_hash, 8, 2);
}

static inline int VOLTAGES_CB2_4_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB2_4_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int TEMPERATURES_CB2_0_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB2_0_identifier, 8, 1);
}

static inline int TEMPERATURES_CB2_0_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB2_0_type_hash, 8, 1);
}

static inline int TEMPERATURES_CB2_0_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 1);
}

static inline int TEMPERATURES_CB2_0_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 1);
}

static inline int TEMPERATURES_CB2_1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB2_1_identifier, 8, 1);
}

static inline int TEMPERATURES_CB2_1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB2_1_type_hash, 8, 1);
}

static inline int TEMPERATURES_CB2_1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 1);
}

static inline int TEMPERATURES_CB2_1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 1);
}

static inline int TEMPERATURES_CB2_2_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB2_2_identifier, 4, 1);
}

static inline int TEMPERATURES_CB2_2_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB2_2_type_hash, 4, 1);
}

static inline int TEMPERATURES_CB2_2_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 4, 1);
}

static inline int TEMPERATURES_CB2_2_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 4, 1);
}

static inline int VOLTAGES_CB3_0_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB3_0_identifier, 8, 2);
}

static inline int VOLTAGES_CB3_0_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB3_0_type_hash, 8, 2);
}

static inline int VOLTAGES_CB3_0_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB3_0_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB3_1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB3_1_identifier, 8, 2);
}

static inline int VOLTAGES_CB3_1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB3_1_type_hash, 8, 2);
}

static inline int VOLTAGES_CB3_1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB3_1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB3_2_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB3_2_identifier, 8, 2);
}

static inline int VOLTAGES_CB3_2_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB3_2_type_hash, 8, 2);
}

static inline int VOLTAGES_CB3_2_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB3_2_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB3_3_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB3_3_identifier, 8, 2);
}

static inline int VOLTAGES_CB3_3_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB3_3_type_hash, 8, 2);
}

static inline int VOLTAGES_CB3_3_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB3_3_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB3_4_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB3_4_identifier, 8, 2);
}

static inline int VOLTAGES_CB3_4_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB3_4_type_hash, 8, 2);
}

static inline int VOLTAGES_CB3_4_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB3_4_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int TEMPERATURES_CB3_0_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB3_0_identifier, 8, 1);
}

static inline int TEMPERATURES_CB3_0_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB3_0_type_hash, 8, 1);
}

static inline int TEMPERATURES_CB3_0_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 1);
}

static inline int TEMPERATURES_CB3_0_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 1);
}

static inline int TEMPERATURES_CB3_1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB3_1_identifier, 8, 1);
}

static inline int TEMPERATURES_CB3_1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB3_1_type_hash, 8, 1);
}

static inline int TEMPERATURES_CB3_1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 1);
}

static inline int TEMPERATURES_CB3_1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 1);
}

static inline int TEMPERATURES_CB3_2_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB3_2_identifier, 4, 1);
}

static inline int TEMPERATURES_CB3_2_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB3_2_type_hash, 4, 1);
}

static inline int TEMPERATURES_CB3_2_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 4, 1);
}

static inline int TEMPERATURES_CB3_2_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 4, 1);
}

static inline int VOLTAGES_CB4_0_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB4_0_identifier, 8, 2);
}

static inline int VOLTAGES_CB4_0_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB4_0_type_hash, 8, 2);
}

static inline int VOLTAGES_CB4_0_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB4_0_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB4_1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB4_1_identifier, 8, 2);
}

static inline int VOLTAGES_CB4_1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB4_1_type_hash, 8, 2);
}

static inline int VOLTAGES_CB4_1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB4_1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB4_2_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB4_2_identifier, 8, 2);
}

static inline int VOLTAGES_CB4_2_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB4_2_type_hash, 8, 2);
}

static inline int VOLTAGES_CB4_2_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB4_2_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB4_3_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB4_3_identifier, 8, 2);
}

static inline int VOLTAGES_CB4_3_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB4_3_type_hash, 8, 2);
}

static inline int VOLTAGES_CB4_3_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB4_3_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB4_4_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB4_4_identifier, 8, 2);
}

static inline int VOLTAGES_CB4_4_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB4_4_type_hash, 8, 2);
}

static inline int VOLTAGES_CB4_4_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB4_4_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int TEMPERATURES_CB4_0_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB4_0_identifier, 8, 1);
}

static inline int TEMPERATURES_CB4_0_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB4_0_type_hash, 8, 1);
}

static inline int TEMPERATURES_CB4_0_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 1);
}

static inline int TEMPERATURES_CB4_0_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 1);
}

static inline int TEMPERATURES_CB4_1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB4_1_identifier, 8, 1);
}

static inline int TEMPERATURES_CB4_1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB4_1_type_hash, 8, 1);
}

static inline int TEMPERATURES_CB4_1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 1);
}

static inline int TEMPERATURES_CB4_1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 1);
}

static inline int TEMPERATURES_CB4_2_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB4_2_identifier, 4, 1);
}

static inline int TEMPERATURES_CB4_2_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB4_2_type_hash, 4, 1);
}

static inline int TEMPERATURES_CB4_2_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 4, 1);
}

static inline int TEMPERATURES_CB4_2_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 4, 1);
}

static inline int VOLTAGES_CB5_0_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB5_0_identifier, 8, 2);
}

static inline int VOLTAGES_CB5_0_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB5_0_type_hash, 8, 2);
}

static inline int VOLTAGES_CB5_0_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB5_0_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB5_1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB5_1_identifier, 8, 2);
}

static inline int VOLTAGES_CB5_1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB5_1_type_hash, 8, 2);
}

static inline int VOLTAGES_CB5_1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB5_1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB5_2_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB5_2_identifier, 8, 2);
}

static inline int VOLTAGES_CB5_2_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB5_2_type_hash, 8, 2);
}

static inline int VOLTAGES_CB5_2_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB5_2_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB5_3_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB5_3_identifier, 8, 2);
}

static inline int VOLTAGES_CB5_3_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB5_3_type_hash, 8, 2);
}

static inline int VOLTAGES_CB5_3_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB5_3_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int VOLTAGES_CB5_4_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, VOLTAGES_CB5_4_identifier, 8, 2);
}

static inline int VOLTAGES_CB5_4_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, VOLTAGES_CB5_4_type_hash, 8, 2);
}

static inline int VOLTAGES_CB5_4_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int VOLTAGES_CB5_4_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int TEMPERATURES_CB5_0_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB5_0_identifier, 8, 1);
}

static inline int TEMPERATURES_CB5_0_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB5_0_type_hash, 8, 1);
}

static inline int TEMPERATURES_CB5_0_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 1);
}

static inline int TEMPERATURES_CB5_0_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 1);
}

static inline int TEMPERATURES_CB5_1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB5_1_identifier, 8, 1);
}

static inline int TEMPERATURES_CB5_1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB5_1_type_hash, 8, 1);
}

static inline int TEMPERATURES_CB5_1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 1);
}

static inline int TEMPERATURES_CB5_1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 1);
}

static inline int TEMPERATURES_CB5_2_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, TEMPERATURES_CB5_2_identifier, 4, 1);
}

static inline int TEMPERATURES_CB5_2_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, TEMPERATURES_CB5_2_type_hash, 4, 1);
}

static inline int TEMPERATURES_CB5_2_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 4, 1);
}

static inline int TEMPERATURES_CB5_2_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 4, 1);
}

static inline int MASTER_SYNC_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, MASTER_SYNC_identifier, 4, 4);
}

static inline int MASTER_SYNC_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, MASTER_SYNC_type_hash, 4, 4);
}

static inline int MASTER_SYNC_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 4, 4);
}

static inline int MASTER_SYNC_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 4, 4);
}

static inline int CELLBOARD_TOKEN_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, CELLBOARD_TOKEN_identifier, 8, 4);
}

static inline int CELLBOARD_TOKEN_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, CELLBOARD_TOKEN_type_hash, 8, 4);
}

static inline int CELLBOARD_TOKEN_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 4);
}

static inline int CELLBOARD_TOKEN_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 4);
}

#include ../../../external/flatcc/flatcc_epilogue.h"
#endif /* SCHEMA_VERIFIER_H */
