# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CELLBOARD_TOKEN(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # CELLBOARD_TOKEN
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CELLBOARD_TOKEN
    def SenderCellboard(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # CELLBOARD_TOKEN
    def Time(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateCELLBOARD_TOKEN(builder, senderCellboard, time):
    builder.Prep(4, 8)
    builder.PrependUint32(time)
    builder.Pad(3)
    builder.PrependUint8(senderCellboard)
    return builder.Offset()
