# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HV_TEMP(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 6

    # HV_TEMP
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HV_TEMP
    def AverageTemp(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # HV_TEMP
    def MaxTemp(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # HV_TEMP
    def MinTemp(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateHV_TEMP(builder, averageTemp, maxTemp, minTemp):
    builder.Prep(2, 6)
    builder.PrependUint16(minTemp)
    builder.PrependUint16(maxTemp)
    builder.PrependUint16(averageTemp)
    return builder.Offset()
