# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SET_CAR_STATUS(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 1

    # SET_CAR_STATUS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SET_CAR_STATUS
    def CarStatusSet(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateSET_CAR_STATUS(builder, carStatusSet):
    builder.Prep(1, 1)
    builder.PrependInt8(carStatusSet)
    return builder.Offset()
