# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class STEER_STATUS_UPDATE(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 3

    # STEER_STATUS_UPDATE
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # STEER_STATUS_UPDATE
    def TractionControl(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # STEER_STATUS_UPDATE
    def Map(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # STEER_STATUS_UPDATE
    def RadioOn(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateSTEER_STATUS_UPDATE(builder, tractionControl, map, radioOn):
    builder.Prep(1, 3)
    builder.PrependBool(radioOn)
    builder.PrependInt8(map)
    builder.PrependInt8(tractionControl)
    return builder.Offset()
