# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MASTER_SYNC(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # MASTER_SYNC
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MASTER_SYNC
    def Time(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateMASTER_SYNC(builder, time):
    builder.Prep(4, 4)
    builder.PrependUint32(time)
    return builder.Offset()
