# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TEMPERATURES_CB0_1(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # TEMPERATURES_CB0_1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TEMPERATURES_CB0_1
    def Temperature8(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TEMPERATURES_CB0_1
    def Temperature9(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # TEMPERATURES_CB0_1
    def Temperature10(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # TEMPERATURES_CB0_1
    def Temperature11(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(3))
    # TEMPERATURES_CB0_1
    def Temperature12(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # TEMPERATURES_CB0_1
    def Temperature13(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(5))
    # TEMPERATURES_CB0_1
    def Temperature14(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))
    # TEMPERATURES_CB0_1
    def Temperature15(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(7))

def CreateTEMPERATURES_CB0_1(builder, temperature8, temperature9, temperature10, temperature11, temperature12, temperature13, temperature14, temperature15):
    builder.Prep(1, 8)
    builder.PrependUint8(temperature15)
    builder.PrependUint8(temperature14)
    builder.PrependUint8(temperature13)
    builder.PrependUint8(temperature12)
    builder.PrependUint8(temperature11)
    builder.PrependUint8(temperature10)
    builder.PrependUint8(temperature9)
    builder.PrependUint8(temperature8)
    return builder.Offset()
