# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TEMPERATURES_CB0_2(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 2

    # TEMPERATURES_CB0_2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TEMPERATURES_CB0_2
    def Temperature16(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TEMPERATURES_CB0_2
    def Temperature17(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))

def CreateTEMPERATURES_CB0_2(builder, temperature16, temperature17):
    builder.Prep(1, 2)
    builder.PrependUint8(temperature17)
    builder.PrependUint8(temperature16)
    return builder.Offset()
